# Generated by Django 5.0.6 on 2024-06-07 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code_en',
            field=models.CharField(max_length=42, null=True, verbose_name='Код доступа к курсу'),
        ),
        migrations.AddField(
            model_name='course',
            name='code_ky',
            field=models.CharField(max_length=42, null=True, verbose_name='Код доступа к курсу'),
        ),
        migrations.AddField(
            model_name='course',
            name='code_ru',
            field=models.CharField(max_length=42, null=True, verbose_name='Код доступа к курсу'),
        ),
        migrations.AddField(
            model_name='course',
            name='department_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.department', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='course',
            name='department_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.department', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='course',
            name='department_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.department', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описания курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описания курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описания курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='name_en',
            field=models.CharField(max_length=42, null=True, verbose_name='Название курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='name_ky',
            field=models.CharField(max_length=42, null=True, verbose_name='Название курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='name_ru',
            field=models.CharField(max_length=42, null=True, verbose_name='Название курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.professor', verbose_name='Профессор'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.professor', verbose_name='Профессор'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.professor', verbose_name='Профессор'),
        ),
        migrations.AddField(
            model_name='department',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описания факультета'),
        ),
        migrations.AddField(
            model_name='department',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описания факультета'),
        ),
        migrations.AddField(
            model_name='department',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описания факультета'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=42, null=True, unique=True, verbose_name='Названия факультета'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ky',
            field=models.CharField(max_length=42, null=True, unique=True, verbose_name='Названия факультета'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ru',
            field=models.CharField(max_length=42, null=True, unique=True, verbose_name='Названия факультета'),
        ),
        migrations.AddField(
            model_name='handinghomework',
            name='assignment_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.homework', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='handinghomework',
            name='assignment_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.homework', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='handinghomework',
            name='assignment_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.homework', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='handinghomework',
            name='feedback_en',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='handinghomework',
            name='feedback_ky',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='handinghomework',
            name='feedback_ru',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='handinghomework',
            name='grade_en',
            field=models.CharField(max_length=5, null=True, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='handinghomework',
            name='grade_ky',
            field=models.CharField(max_length=5, null=True, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='handinghomework',
            name='grade_ru',
            field=models.CharField(max_length=5, null=True, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='handinghomework',
            name='student_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.student', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='handinghomework',
            name='student_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.student', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='handinghomework',
            name='student_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.student', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='handinghomework',
            name='submission_date_en',
            field=models.DateTimeField(null=True, verbose_name='Время сдачи'),
        ),
        migrations.AddField(
            model_name='handinghomework',
            name='submission_date_ky',
            field=models.DateTimeField(null=True, verbose_name='Время сдачи'),
        ),
        migrations.AddField(
            model_name='handinghomework',
            name='submission_date_ru',
            field=models.DateTimeField(null=True, verbose_name='Время сдачи'),
        ),
        migrations.AddField(
            model_name='homework',
            name='course_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='homework',
            name='course_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='homework',
            name='course_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='homework',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описания задания'),
        ),
        migrations.AddField(
            model_name='homework',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описания задания'),
        ),
        migrations.AddField(
            model_name='homework',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описания задания'),
        ),
        migrations.AddField(
            model_name='homework',
            name='due_date_en',
            field=models.DateTimeField(null=True, verbose_name='Дедлайн'),
        ),
        migrations.AddField(
            model_name='homework',
            name='due_date_ky',
            field=models.DateTimeField(null=True, verbose_name='Дедлайн'),
        ),
        migrations.AddField(
            model_name='homework',
            name='due_date_ru',
            field=models.DateTimeField(null=True, verbose_name='Дедлайн'),
        ),
        migrations.AddField(
            model_name='homework',
            name='title_en',
            field=models.CharField(max_length=42, null=True, verbose_name='Название задания'),
        ),
        migrations.AddField(
            model_name='homework',
            name='title_ky',
            field=models.CharField(max_length=42, null=True, verbose_name='Название задания'),
        ),
        migrations.AddField(
            model_name='homework',
            name='title_ru',
            field=models.CharField(max_length=42, null=True, verbose_name='Название задания'),
        ),
        migrations.AddField(
            model_name='professor',
            name='bio_en',
            field=models.TextField(null=True, verbose_name='Биография профессора'),
        ),
        migrations.AddField(
            model_name='professor',
            name='bio_ky',
            field=models.TextField(null=True, verbose_name='Биография профессора'),
        ),
        migrations.AddField(
            model_name='professor',
            name='bio_ru',
            field=models.TextField(null=True, verbose_name='Биография профессора'),
        ),
        migrations.AddField(
            model_name='professor',
            name='department_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.department', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='professor',
            name='department_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.department', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='professor',
            name='department_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.department', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='professor',
            name='title_en',
            field=models.CharField(max_length=32, null=True, verbose_name='Уроки'),
        ),
        migrations.AddField(
            model_name='professor',
            name='title_ky',
            field=models.CharField(max_length=32, null=True, verbose_name='Уроки'),
        ),
        migrations.AddField(
            model_name='professor',
            name='title_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Уроки'),
        ),
        migrations.AddField(
            model_name='professor',
            name='user_en',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профессор'),
        ),
        migrations.AddField(
            model_name='professor',
            name='user_ky',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профессор'),
        ),
        migrations.AddField(
            model_name='professor',
            name='user_ru',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профессор'),
        ),
        migrations.AddField(
            model_name='regcourse',
            name='course_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='regcourse',
            name='course_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='regcourse',
            name='course_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='regcourse',
            name='date_enrolled_en',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='regcourse',
            name='date_enrolled_ky',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='regcourse',
            name='date_enrolled_ru',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='regcourse',
            name='grade_en',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='regcourse',
            name='grade_ky',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='regcourse',
            name='grade_ru',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='regcourse',
            name='student_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.student', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='regcourse',
            name='student_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.student', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='regcourse',
            name='student_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.student', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='room',
            name='building_en',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='building_ky',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='building_ru',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity_en',
            field=models.PositiveSmallIntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity_ky',
            field=models.PositiveSmallIntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity_ru',
            field=models.PositiveSmallIntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_number_en',
            field=models.PositiveSmallIntegerField(default=0, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_number_ky',
            field=models.PositiveSmallIntegerField(default=0, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_number_ru',
            field=models.PositiveSmallIntegerField(default=0, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='classroom_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.room', verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='classroom_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.room', verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='classroom_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.room', verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='course_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='course_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='course_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day_of_week_en',
            field=models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day_of_week_ky',
            field=models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day_of_week_ru',
            field=models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_time_en',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_time_ky',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_time_ru',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time_en',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time_ky',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time_ru',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='department_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.department', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='student',
            name='department_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.department', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='student',
            name='department_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.department', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_date_en',
            field=models.DateField(null=True, verbose_name='Дата начала обучения'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_date_ky',
            field=models.DateField(null=True, verbose_name='Дата начала обучения'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_date_ru',
            field=models.DateField(null=True, verbose_name='Дата начала обучения'),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_date_en',
            field=models.DateField(null=True, verbose_name='Дата окончания обучения'),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_date_ky',
            field=models.DateField(null=True, verbose_name='Дата окончания обучения'),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_date_ru',
            field=models.DateField(null=True, verbose_name='Дата окончания обучения'),
        ),
        migrations.AddField(
            model_name='student',
            name='user_en',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='student',
            name='user_ky',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='student',
            name='user_ru',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
    ]
